site_name: Hestia.ai Outreach - Data Harvest 2022
site_url: https://hestiaai.github.io/outreach
site_author: Paul-Olivier Dehaye & team
site_description: Web pages for special outreach project for [Hestia.ai](https://www.hestia.ai/), the data solutions company based in Geneva, Switzerland.

nav:
  - Hestia.ai: https://hestia.ai/
  - Dataharvest: https://dataharvest.eu/

theme:
  name: null
  custom_dir: 'cinder'